# Generated by Django 3.0.3 on 2020-02-12 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_name', models.CharField(max_length=200)),
                ('content_factor', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_name', models.CharField(max_length=200)),
                ('step_order', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='RealCube',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('real_cube_value', models.IntegerField(default=0)),
                ('real_cube_publish_date', models.DateTimeField(auto_now_add=True)),
                ('real_cube_channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datamodel.Channel')),
                ('real_cube_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datamodel.Content')),
                ('real_cube_step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datamodel.Step')),
            ],
        ),
        migrations.CreateModel(
            name='IdealCube',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ideal_cube_value', models.IntegerField(default=0)),
                ('ideal_cube_channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datamodel.Channel')),
                ('ideal_cube_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datamodel.Content')),
                ('ideal_cube_step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datamodel.Step')),
            ],
        ),
    ]
